### ISSUE TITLE
docker install problem

### ISSUE THREAD

**Issue by trombose009** [mtrossbach/noah-mqtt#13]
Sorry, noob question. I try to install noah-mqtt using following command in my rpi docker environment:
sudo docker run —name noah-mqtt -e GROWATT_USERNAME=myusername -e GROWATT_PASSWORD=xxxxxxx -e MQTT_HOST=192.168.178.44 -e MQTT_PORT=1883 ghcr.io/mtrossbach/noah-mqtt:latest

I get the error: 
docker: invalid reference format.
See 'docker run --help'.

please help   :P :D

**Comment by trombose009** [comment]
hab es selbst gefunden. in dem hier publizierten install string ist statt zwei striche vor "name"    ein einzelner, langer strich. Das könnte man mal korrigieren.

**Comment by trombose009** [comment]
> Vielen Dank für den Hinweis! Ich werde den Install-String anpassen, damit das in Zukunft nicht mehr passiert. 😊

jetzt ist nur noch ein strich da. müsste es nicht  --name heißen?  also ich meinte so musste ich das machen. aber hey, es ist schon wieder 24h her. kann mich auch irren :P

**Comment by mtrossbach** [comment]
Absolut richtig ... bin wohl noch nicht so richtig wach 🙈

**Comment by trombose009** [comment]
> Absolut richtig ... bin wohl noch nicht so richtig wach 🙈

offenbar findet auch mal ein blindes Huhn (ich) ein Korn. Ich bin es gewohnt für meine noob Fragen oft geprügelt zu werden. "Verwenden Sie die Suchfunktion," "Lesen Sie die FAQ," "Lernen Sie bitte Programmieren."
Jetzt darf ich auch mal Glückhaben. Dem Schicksal sei Dank. :D
