### ISSUE TITLE
Probleme beim Passwort und Startparameter Docker

### ISSUE THREAD

**Issue by warp4242** [mtrossbach/noah-mqtt#14]
Moin !

Ein tolles Projekt, welches ich ab sofort nutzen werde, allerdings nicht für HomeAssistent, sondern um mir in Grafana Diagramme zu bauen. 

Nun zu meinen Problemen:

- Ich hatte Probleme mein Passwort in die Docker-Befehlszeile einzutragen, da am Ende ein Sonderzeichen stand, welches die bash versucht hat zu interpretieren. Ich habe es gelöst, in dem ich die Werte für die Environment-Variablen in **""** gesetzt habe:

`docker run --name noah-mqtt -e "GROWATT_USERNAME=Accountname" -e "GROWATT_PASSWORD=Passw0rd!!" -e "MQTT_HOST=localhost" -e "MQTT_PORT=1883" ghcr.io/mtrossbach/noah-mqtt:latest`

Damit bekomme ich über den MQTT-Explorer schonmal Werte heraus.

- außerdem habe ich das **-d** dazu gepackt, damit es im Hintergrund mit den anderen Container laufen kann:

`docker run -d --name noah-mqtt -e "GROWATT_USERNAME=Accountname" -e "GROWATT_PASSWORD=Passw0rd!!" -e "MQTT_HOST=localhost" -e "MQTT_PORT=1883" ghcr.io/mtrossbach/noah-mqtt:latest`

Spricht für dich was gegen **-d** oder die **""** ?

Mach weiter so, bin gerne für Tests bereit.

Hardy

**Comment by mtrossbach** [comment]
Hallo Hardy!

Vielen Dank für dein Feedback und die netten Worte! Freut mich, dass du das Projekt nutzt, um deine Grafana-Diagramme zu bauen – klingt nach einer coolen Anwendung.

Zu deinen Fragen: Die Anführungszeichen um die Environment-Variablen sind absolut in Ordnung und sogar empfohlen, wenn Sonderzeichen im Spiel sind. Das verhindert genau die Probleme, die du beschrieben hast.

Das -d-Flag ist auch völlig okay, wenn du den Container im Hintergrund laufen lassen möchtest. Da spricht nichts dagegen.

Wenn du weitere Anmerkungen oder Ideen hast, immer her damit.

Beste Grüße und viel Spaß mit dem Projekt!

Markus
