### ISSUE TITLE
Upon restart, getting a huge spike in energy dashboard

### ISSUE THREAD

**Issue by rschoell** [mtrossbach/noah-mqtt#19]
Hi Markus, 
using your script with docker and it works flawless, except if Home Assistant needs to restart. 
In the statistics, I'm seeing a huge spike in "NOAH 2000 Generation total", as it goes once down to a very low value and up again to my 200+ kWh produced over time. 
I'm able to fix this by setting the mqtt message with MQTT explorer to retain. 

Would it be possible for you to change the submitted mqtt messages for the main to be retained? 

Many thanks
Ralph

**Comment by mtrossbach** [comment]
Hi Ralph,

I also experience this sometime myself ... I am not sure what is causing the issue yet. Do you have by chance any log outputs of noah-mqtt showing this spike?

Thank you!

Best regards, Markus

**Comment by rschoell** [comment]
Hallo Markus, 
ich finde ich Log leider keine Anhaltspunkte. Ich habe seit kurzem auch auf die 2024.9.3 updaten können, da ein lästiger Bug mit Tibber endlich gefixt ist. Seitdem sehe ich aktuell keine derlei Spikes mehr, wenn ich restarte. 
Für den Fall der Fälle habe ich mir trotzdem schon mal einen mqtt.publish Action gebaut, die ich vor dem Restart einbauen könnte:

`action: mqtt.publish`
`data:`
`  evaluate_payload: false`
`  qos: "0"`
`  retain: true`
`  topic: noah2mqtt/0PVP40ZR14QT0008`
`  payload: >-`
`    { "output_w": {{states('sensor.noah_2000_output_power')}}, "solar_w":`
`    {{states('sensor.noah_2000_solar_power')}}, "soc":`
`    {{states('sensor.noah_2000_soc')}}, "charge_w":`
`    {{states('sensor.noah_2000_charging_power')}}, "discharge_w":`
`    {{states('sensor.noah_2000_discharge_power')}}, "battery_num":`
`    {{states('sensor.noah_2000_number_of_batteries')}}, "generation_total_kwh":`
`    {{states('sensor.noah_2000_generation_total')}}, "generation_today_kwh":`
`    {{states('sensor.noah_2000_generation_today')}}, "work_mode":`
`    "battery_first", "status": "online" }`

Damit würde ich noch mal ein retained Message mit allen aktuellen Werten rüber schicken und hoffe, dass der MQTT Server dann im Anschluss die richtigen Daten wieder aufgreift. 
Ich würd's aktuell mal schließen. 

Danke Dir. 
Gruß Ralph
