### ISSUE TITLE
Wie und wo kann ich diese Tool einrichten? HILFE...

### ISSUE THREAD

**Issue by Dandoo1** [mtrossbach/noah-mqtt#21]
Hallo zusammen,

Wie und Wo kann ich dieses Tool einrichten? Schön wäre es wenn es irgendwie auf meinem Raspbi4 laufen würde wo schon mein IOBroker läuft der die MQTT Daten auch gleich verarbeiten soll.

Kann mir da jemand deutschsprachig weiter helfen?

THX

**Comment by rschoell** [comment]
Für das Tool gibt's 2 Varianten, es laufen zu lassen. Entweder als Plugin in HA, was aber bei Dir rausfällt, oder in Docker als Container. 
Da ich jetzt leider nicht weiß, wie Dein Raspi4 aufgesetzt ist, würde ich aber vermuten, dass Du erst irgendwo Docker zum Fliegen bringen musst, und dann über docker pull Dir dieses Projekt kopieren kannst. 
Ich verwende z.B. zusätzlich zu Docker noch Portainer als grafische Oberfläche, steuere aber trotzdem das meiste über Docker selbst.

**Comment by mtrossbach** [comment]
Hat jemand zufällig Erfahrung mit dem IOBroker und der Einbindung von MQTT, der hier helfen kann?

**Comment by rschoell** [comment]
Hallo @Dandoo1,

bisher kamen leider keine weiteren Info's zu Deiner Infrastruktur. Damit ist es leider sehr schwierig, Dich zu unterstützen. Generell müssten wir ja bei Dir nur den Service von Markus zum Fliegen bekommen, damit Du in IOBroker die Daten abgreifen kannst.
