### ISSUE TITLE
How to determine when NOAH is offline?

### ISSUE THREAD

**Issue by MartinGoX** [mtrossbach/noah-mqtt#22]
Hello Markus,
I'm still successfully using your integration to control my NOAH system (in the meantime also by having a "Nulleinspeisung" running with a HM800 micro inverter).
Sometimes the NOAH loose the network connection - the ShinePhone app shows 'Offline' as the main status.
Is there any possibility to get this status information via the MQTT interface as well?
Or is the only way to 'calculate' such status by checking the 'last modified time stamp' for e.g. the battery temperature entity - fi it is older than e.g. 1 hour the NOAH might be offline...
Thanks a lot for your feedback and best regards
Martin

**Comment by mtrossbach** [comment]
Hi Martin,

good idea! I’ll look into whether the Growatt API can provide the status information. If it is in the app it should be possible.

I’ll get back to you as soon as I have more information.

Best regards, Markus

**Comment by mtrossbach** [comment]
Good news, the information is available in the api. I added it to version 0.0.22 🎉

**Comment by MartinGoX** [comment]
Great, Markus, thank you.
As soon as the update is downloadable I will try.

Another way I found out is to use the 'Ping' integration - this will show now 'Unconnected' for my current NOAH status.
Do you also have the problem of loosed Wifi connection? My NOAH is now 2 days offline and I have no idea how to get it connected again...

**Comment by msmthng** [comment]
My noah was neuer offline so für, but my unifo accesüpint is clone to irre, iam also using a static Chanel.

Aß gar i can remember in https://www.photovoltaikforum.com/thread/224226-growatt-noah-2000-plug-play-speicher-f%C3%BCr-balkonkraftwerk

Tthere were some issue with changing Chanel and also 5g mentioned.

**Comment by mtrossbach** [comment]
I’ve also set up my NOAH device on a dedicated IoT WiFi network with a static channel on the 2.4 GHz band. So far, I haven’t experienced any connection drops, which might be due to the dedicated setup.

**Comment by MartinGoX** [comment]
Markus and msmthng: thank you for your hints. Maybe it's now the time for me as well to think about a specific peace of hardware to connect all my IoT devices with.
Do you have any recommendations which type of access point is "the best" for such a purpose?

**Comment by mtrossbach** [comment]
I don't actually use separate hardware specifically for my IoT network. Instead, I created a dedicated IoT WiFi network using a second SSID on my existing Ubiquiti Unifi Access Points. This approach allows me to segment my IoT devices without the need for additional physical hardware.

If you're considering this setup, it's good to know that you can do it with other vendors' access points as well. It mainly depends on how much effort you’re willing to put into configuring and maintaining it. For example, Unifi works best if you have a network controller running, which does mean hosting an additional service somewhere (e.g., on a Raspberry Pi, your PC, or a dedicated device).

If you're open to investing in the Unifi ecosystem, it’s quite powerful and gives you a lot of flexibility. But even with other brands, as long as they support multiple SSIDs and VLANs, you should be able to achieve a similar setup.

**Comment by MartinGoX** [comment]
Markus, thank you for your explanation.
I roughly read about Unifi, but I think to understand that the configuration is more complex and difficualt as it is for a Fritzbox. I understand and know basics about network stuff but not sure to extend my knowledge too much for that. So I will investigate what the best for me will be...

Btw: I just installed v0.0.22 with the new 'Connectivity' entity - nice! Thank you for that.
