### ISSUE TITLE
Aktion Wert für Growatt Noah System Output Power setzen funktioniert nur zum Teil 

### ISSUE THREAD

**Issue by tester277** [mtrossbach/noah-mqtt#24]
Wenn über Home Assistent ein neuer Power Wert gesetzt wird, wird dieser zwar übernommen. Aber die Änderung wird trotzdem nicht aktiviert. Kontrolle in shine App: hier wird weiter der alte Wert angezeigt. Unter Einstellungen (shine) System Standardausgangsleistung sieht man jedoch den neuen Wert. Den könnte man mit bestätigen auch übernehmen. Dieser Schritt fehlt beim setzen über mqtt.

**Comment by mtrossbach** [comment]
Hallo,

danke für das Feedback! Bist du sicher, dass du keinen Zeitplan erstellt hast? Ein Zeitplan überschreibt immer die Einstellung für die Systemausgangsleistung. Ein solcher Zeitplan wird z. B. automatisch erstellt, wenn man einen Arbeitsmodus wie „Batterie zuerst“ auswählt. Dies könnte erklären, warum der Wert zwar in den Einstellungen angezeigt wird, aber nicht direkt übernommen wird. 

Kannst du das bitte prüfen und uns Rückmeldung geben?

Vielen Dank!

**Comment by tester277** [comment]
Hallo, Danke für Deine tolle Arbeit und deine ausführliche Antwort. Deine Vermutungen sind korrekt.
Ich habe Zeitpläne erstellt. Dann kann ich die Steuerung in der Nacht (Power je nach Akkustand) besser über HomeAssistent betreiben.
Vielen Dank

**Comment by orimate** [comment]
Hallo,

Danke für deine tolle Arbeit. Ich würde dich gerne auf ein Bier einladen. Ich unterstütze oft solche Projekte.

Meine Frage ist:
Ich habe gelesen, dass beim manchen Inverter und Speicher, die gesetzte Werte sind in einem persistent Speicher (Flash) reingeschrieben, dass nach dem Bootvorgang die Werte wieder gelesen werden können. D. h. wenn man oft zum Beispiel Output_power umschreibt, dann wird der Flash schnell kaputtgeschrieben. Es geht um eine Nulleinspeisung hinzukriegen, dafür würde ich regelmäßig mit Nodered die Ausgangsleistung eventuell minute weise umstellen. Hast du in die Richtung Infos wie es beim Noha funktioniert? Danke und Grüße
