### ISSUE TITLE
Energy Dashboard integration

### ISSUE THREAD

**Issue by sdekker90** [mtrossbach/noah-mqtt#27]
Thanks for writing this add-on for Home Assistant! I'd like to add my batteries to the Energy Dashboard, but I am a little confused as to what is what.

### **Current behaviour**
I am seeing the following entities:

**Generation Total**
Is this the total that was charged into the batteries, or the total generated by the solar panels? 

**Solar Power**
Just a current value in watts, not tracked daily

**Charge Power**
Just a current value in watts, not tracked daily

### **Preferred behaviour**
For the energy dashboard I would basically need the following:

Increasing total charged into batteries, today, in kWh
Increasing total discharged to the net from the batteries, today, in kWh
Increasing total delivered to the net that bypassed the batteries, today, in kWh

Could you look into this? Much appreciated :)

**Comment by mtrossbach** [comment]
Hi @sdekker90,

Thanks for the feedback! I understand the desire for those specific metrics in the Energy Dashboard.  Unfortunately, Growatt only provides the "Generation Total", "Generation Today", "Solar Power", and "Charge/Discharge Power" values.

As you mentioned, calculating "Increasing total discharged to the net from the batteries" and "Increasing total delivered to the net that bypassed the batteries" requires additional data that this device doesn't provide. If your inverter exports this information, you might be able to utilize it for more accurate calculations.

In my setup I work around the issue by using the **Noah Generation Total** as Solar Input as well as input to the battery. Then I use the output data from inverter as output data for the battery. This way I got a quite good result on my battery dashboard. Maybe this is something you can try as well.

If the device's API expands in the future to include more detailed metrics, I'll definitely revisit this and implement the preferred behavior.

In the meantime, I hope the current implementation provides some useful insights into your solar and battery system.

Thanks again for your input!
