### ISSUE TITLE
MQTT Command to set output_power_w

### ISSUE THREAD

**Issue by Snowless3** [mtrossbach/noah-mqtt#34]
Hi everyone,
how look like the MQTT Command to set the output power?

I tried this topic´s but it doesn't work:
noah2mqtt/serialXXXXXX/parameters/output_power_w
noah2mqtt/serialXXXXXX/parameters/set/output_power_w
![MQTT_Explorer](https://github.com/user-attachments/assets/4cc1a96e-99a1-4d4f-baf5-6d57cffcbf20)
Thx a lot

**Comment by syngron** [comment]
See here
https://github.com/mtrossbach/noah-mqtt/issues/25
