### ISSUE TITLE
Add MQQT Username and password (hashed, too)

### ISSUE THREAD

**Issue by Syr0** [mtrossbach/noah-mqtt#36]
can be done vie .env already, but should be part of the setup procedure imo

**Comment by mtrossbach** [comment]
Hi! Thank you for your input. I am not completely sure what do you mean with setup procedure?

**Comment by Syr0** [comment]
nvm. I used chatgpt to just write that stuff to a local config file (.env) so in docker, the plain passwords are not visible on the UI (env variables)
