### ISSUE TITLE
system output doesn't work

### ISSUE THREAD

**Issue by Buster2k6** [mtrossbach/noah-mqtt#40]
Hello, I received my Noah 2000 today and connected it to Home Assistant via noah-mqtt. All values are coming through, but when I set the system output, the Noah doesn't respond. 

The MQTT signal goes to the broker,I could see that using MQTT Explorer 
Topic  
noah2mqtt/serialnumber/BAT0/parameters/set
({"charging_limit":100,"discharge_limit":10,"output_power_w":213}). 

I can control the Noah without issues via the app. 
Does anyone know what could be causing this? 
Thank you very much!

![Bildschirmfoto 2024-11-08 um 16 02 19](https://github.com/user-attachments/assets/7b974469-a9be-4ee6-8cc3-b526533b0d41)

**Comment by Buster2k6** [comment]
Okay, I found out why it wasn't working. You have to disable the operation mode, only then does the Noah respond to the system default output power.

**Comment by Buster2k6** [comment]
you must delete the time period by swiping left and then press delete, thats it.

**Comment by thomasramm** [comment]
oh, so easy. 
Now it works
:-)
