### ISSUE TITLE
MQTT_PASSWORD is not working

### ISSUE THREAD

**Issue by JochenKlenk** [mtrossbach/noah-mqtt#5]
Hi, the docker run with an mqtt password is not working I get an error

Also I can see that it is not using the password when it try to login. User it takes

docker run --name noah-mqtt -e GROWATT_USERNAME=xxxxx-e GROWATT_PASSWORD=xxxx -e MQTT_HOST=x.x.x.x -e MQTT_PORT=1883 -e MQTT_USERNAME=xxx -e MQTT_PASSWORD=xxxx ghcr.io/mtrossbach/noah-mqtt:latest

{"time":"2024-07-31T09:42:01.149591498Z","level":"INFO","msg":"set log level","level":"debug"}
{"time":"2024-07-31T09:42:01.149683308Z","level":"INFO","msg":"noah-mqtt started","version":"0.0.11"}
{"time":"2024-07-31T09:42:01.149730704Z","level":"INFO","msg":"running as","username":"gouser","uid":"1000"}
{"time":"2024-07-31T09:42:01.149743722Z","level":"INFO","msg":"connecting to mqtt broker","host":"x.x.x.x","port":1883,"clientId":"noah-mqtt","username":"xxxx"}
panic: not Authorized

goroutine 1 [running]:
main.connectMqtt({{0xc00001a052, 0xe}, 0x75b, {0x71a1f0, 0x9}, {0xc00001a03e, 0x4}, {0xc00001a026, 0x8}, {0x71a1f9, ...}}, ...)
        /home/runner/work/noah-mqtt/noah-mqtt/cmd/noah-mqtt/main.go:73 +0x610
main.main()
        /home/runner/work/noah-mqtt/noah-mqtt/cmd/noah-mqtt/main.go:31 +0x338

Can someone help here.
Thanks

**Comment by mtrossbach** [comment]
Hi,

thank you for reporting this issue with the MQTT password. I've identified the problem and have hopefully resolved it in version `v0.0.12`.  

Please update your Docker image to use the latest version. You can do this by pulling the updated image with the following command
```
docker pull ghcr.io/mtrossbach/noah-mqtt:latest
```
or use the version tag `v0.0.12` directly.

If you continue to experience issues, please let me know, and I will investigate further.
