### ISSUE TITLE
Directly as an Addon for Home Assistant?

### ISSUE THREAD

**Issue by acidburn78** [mtrossbach/noah-mqtt#6]
Hi @mtrossbach,

would it be possible to make these as an Addon for Home Assistant? 
Supervisor Addons are also Docker Container, so it could run on the same Hardware

**Comment by mtrossbach** [comment]
Hi @acidburn78,

Great news! I've created a Home Assistant add-on for this project. You can find it in the repository [https://github.com/mtrossbach/hassio-addons](https://github.com/mtrossbach/hassio-addons).

Please note that the add-on is currently under construction and will be updated with better metadata and documentation in the next days. I would appreciate it if you could test the add-on and let me know how it works for you.

Thanks for the suggestion and support!
