### ISSUE TITLE
Error in latest version 0.0.19

### ISSUE THREAD

**Issue by rschoell** [mtrossbach/noah-mqtt#7]
First of all thanks for your great container, helping a lot of folks, to get info's we're not able to get out of Home assistant directly.
I've got your product installed since 0.0.12 in Docker. Now I've updated to your latest, as I was interested in your improvements towards steerability. 
Once installed, I'm getting these errors in the log:

![image](https://github.com/user-attachments/assets/fdc87a97-34e6-4029-ba13-fbd9d484a40d)

before on version 0.0.18 it was working flawless. 
Also please have a look at line 2, as this always reports it's version 0.0.12. 

many thanks
Ralph

**Comment by mtrossbach** [comment]
Hi @rschoell,

thank you for using the application and providing feedback 👍 

I just uploaded v0.0.20 ... I hope this fixes the crash for you.  I would appreciate it if you could test it and provide feedback.
Concerning the wrong version number I have to look into it in the next days.

**Comment by rschoell** [comment]
Hi @mtrossbach, 

yep, your release 0.0.20 fixes this issue and now provides the control for the output control. 
Really looking forward to your future development in allowing everyone full control through MQTT/Home Assistant. 

Let me know, if I can help testing. 
Many thanks
Ralph

**Comment by rschoell** [comment]
closing
